'use strict';

const { ROLES } = require('./roles');

/**
 * Permission matrix for RBAC.
 * Each resource maps to arrays of allowed roles per action.
 * Future modules: add new resource keys here.
 */
const PERMISSIONS = Object.freeze({
  users: {
    read:   [ROLES.ADMIN],
    create: [ROLES.ADMIN],
    update: [ROLES.ADMIN],
    delete: [ROLES.ADMIN],
  },
  products: {
    read:   [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.SALES_USER, ROLES.PURCHASE_USER, ROLES.MANUFACTURING_USER, ROLES.INVENTORY_MANAGER],
    create: [ROLES.ADMIN, ROLES.BUSINESS_OWNER],
    update: [ROLES.ADMIN, ROLES.BUSINESS_OWNER],
    delete: [ROLES.ADMIN, ROLES.BUSINESS_OWNER],
  },
  inventory: {
    read:   [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.SALES_USER, ROLES.PURCHASE_USER, ROLES.MANUFACTURING_USER, ROLES.INVENTORY_MANAGER],
    create: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.INVENTORY_MANAGER],
    update: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.INVENTORY_MANAGER],
    delete: [ROLES.ADMIN],
  },
  dashboard: {
    read:   [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.SALES_USER, ROLES.PURCHASE_USER, ROLES.MANUFACTURING_USER, ROLES.INVENTORY_MANAGER],
  },
  customers: {
    read:   [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.SALES_USER, ROLES.INVENTORY_MANAGER],
    create: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.SALES_USER],
    update: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.SALES_USER],
    delete: [ROLES.ADMIN, ROLES.BUSINESS_OWNER],
  },
  sales: {
    read:   [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.SALES_USER],
    create: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.SALES_USER],
    update: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.SALES_USER],
    delete: [ROLES.ADMIN, ROLES.BUSINESS_OWNER],
  },
  deliveries: {
    read:   [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.SALES_USER, ROLES.INVENTORY_MANAGER],
    create: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.INVENTORY_MANAGER],
    update: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.INVENTORY_MANAGER],
    delete: [ROLES.ADMIN],
  },
  movements: {
    read:   [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.SALES_USER, ROLES.INVENTORY_MANAGER],
  },
  purchase: {
    read:   [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.PURCHASE_USER],
    create: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.PURCHASE_USER],
    update: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.PURCHASE_USER],
    delete: [ROLES.ADMIN, ROLES.BUSINESS_OWNER],
  },
  manufacturing: {
    read:   [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.MANUFACTURING_USER],
    create: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.MANUFACTURING_USER],
    update: [ROLES.ADMIN, ROLES.BUSINESS_OWNER, ROLES.MANUFACTURING_USER],
    delete: [ROLES.ADMIN, ROLES.BUSINESS_OWNER],
  },
});

module.exports = { PERMISSIONS };
