'use strict';

const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
  BUSINESS_OWNER: 'BUSINESS_OWNER',
  SALES_USER: 'SALES_USER',
  PURCHASE_USER: 'PURCHASE_USER',
  MANUFACTURING_USER: 'MANUFACTURING_USER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
});

const ROLE_LIST = Object.values(ROLES);

module.exports = { ROLES, ROLE_LIST };
